# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IHgRbVHgzCJf86jN0jqhZf4db42k67JZ
"""

def calculate_sum(*args):
    result = sum(args)
    return result

calculate_sum(1,2,3)

