# -*- coding: utf-8 -*-
"""mk_func.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vEjVKUygy2MGBLniJoJJB4tUskLVvoyS
"""

def reverse_string(l):
  l = l[::-1]
  return l

